/** Expo Router hrefs — single source for navigation strings */
export const ROUTES = {
  welcome: '/',
  appHome: '/(app)/(tabs)/home',
  appSleep: '/(app)/(tabs)/sleep',
  appSleepTracker: '/(app)/sleep-tracker',
  appRelax: '/(app)/(tabs)/relax',
  appMind: '/(app)/(tabs)/relax',
  appReport: '/(app)/(tabs)/report',
  appRecovery: '/(app)/(tabs)/recovery',
  appEyeRelax: '/(app)/(tabs)/eye-relax',
  appProfile: '/(app)/(tabs)/profile',
  appHistory: '/(app)/history',
  appAchievements: '/(app)/achievements',
  appEditProfile: '/(app)/edit-profile',
  appPremium: '/(app)/premium',
  appAudioPlayer: '/(app)/audio-player',
  appBoxBreathing: '/(app)/stress/box-breathing',
  appBodyScan: '/(app)/stress/body-scan',
  appJournal: '/(app)/stress/journal',
  appEyeExercise: (id: string) => `/(app)/eye-exercise/${id}` as const,
  appEyeGame: (id: string) => `/(app)/eye-game/${id}` as const,
  appCvsProtocol: '/(app)/cvs-protocol',
  appDichopticScreen: '/(app)/dichoptic-screen',
  appEyeBreak: '/(app)/eye-break',
  appGrounding: '/(app)/stress/grounding',
  appCalmWave: '/(app)/stress/calm-wave',
  appTensionRelease: '/(app)/stress/tension-release',
  appBreathe:        '/(app)/stress/breathe',
  appBreatheSession: '/(app)/stress/breathe-session',
  appBreatheDone:    '/(app)/stress/breathe-done',
  appAlarmSettings:  '/(app)/alarm-settings',
  appRelaxPlayer:    '/(app)/relax/player',
  appRelaxLibrary:   '/(app)/relax/library',
  appRelaxCompletion: '/(app)/relax/completion',
  authOnboarding: '/(auth)/onboarding',
  authAgeInput: '/(auth)/age-input',
  authSignIn: '/(auth)/sign-in',
  authCreateAccount: '/(auth)/create-account',
  authForgotPassword: '/(auth)/forgot-password',
} as const;
