/** Expo Router hrefs — single source for navigation strings */
export const ROUTES = {
  welcome: '/',
  appHome: '/(app)/(tabs)/home',
  appSleep: '/(app)/(tabs)/sleep',
  appSleepTracker: '/(app)/sleep-tracker',
  appRelax: '/(app)/(tabs)/relax',
  appMind: '/(app)/(tabs)/relax',
  appReport: '/(app)/(tabs)/report',
  appRecovery: '/(app)/(tabs)/recovery',
  appEyeRelax: '/(app)/(tabs)/eye-relax',
  appChallenges: '/(app)/(tabs)/challenges',
  appProfile: '/(app)/(tabs)/profile',
  appHistory: '/(app)/history',
  appAchievements: '/(app)/achievements',
  appEditProfile: '/(app)/edit-profile',
  appPremium: '/(app)/premium',
  appAudioPlayer: '/(app)/audio-player',
  // Breathing entry points open the Relax player (the one real breathing
  // engine) — the old standalone Box Breathing / Calm Wave screens are gone.
  appBoxBreathing: '/(app)/relax/player?sessionId=box-breathing',
  appBodyScan: '/(app)/stress/body-scan',
  appJournal: '/(app)/stress/journal',
  appEyeExercise: (id: string) => `/(app)/eye-exercise/${id}` as const,
  appEyeGame: (id: string) => `/(app)/eye-game/${id}` as const,
  appCvsProtocol: '/(app)/cvs-protocol',
  appDichopticScreen: '/(app)/dichoptic-screen',
  appEyeBreak: '/(app)/eye-break',
  appGrounding: '/(app)/stress/grounding',
  appCalmWave: '/(app)/relax/player?sessionId=calm-flow',
  appTensionRelease: '/(app)/stress/tension-release',
  appBreathe:        '/(app)/stress/breathe',
  appAlarmSettings:  '/(app)/alarm-settings',
  appRelaxPlayer:    '/(app)/relax/player',
  appRelaxLibrary:   '/(app)/relax/library',
  appRelaxCompletion: '/(app)/relax/completion',
  authOnboarding: '/(auth)/onboarding',
  authAgeInput: '/(auth)/age-input',
  authSignIn: '/(auth)/sign-in',
  authCreateAccount: '/(auth)/create-account',
  authForgotPassword: '/(auth)/forgot-password',
} as const;
